version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    image: myaccount/nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - wwwroot:/wwwroot
  webpack:
    build:
      context: .
      dockerfile: docker/Dockerfile.webpack
    image: myaccount/webpack
    container_name: webpack
    ports:
      - "35729:35729"
    volumes:
      - .:/app
      - ./webpack.config.js:/app/webpack.config.js
      - /app/node_modules
      - wwwroot:/app/public/build
    links:
      - mock:mock
  mock:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock
    image: myaccount/mock
    container_name: mock
    ports:
      - "4000:4000"
    volumes:
      - ./docker/api.raml:/raml/api.raml
volumes:
  wwwroot:
    driver: local