FROM node:8.0.0-alpine
MAINTAINER Mark Kreyman <mark.kreyman@sling.com>

RUN apk update && apk add git
RUN npm config set registry https://artifactory.global.dish.com/artifactory/api/npm/npm-remote && \
    npm config set strict-ssl false && \
    npm install -g osprey-mock-service

WORKDIR /raml
VOLUME /raml
ADD docker/api.raml /raml
EXPOSE 4000

CMD osprey-mock-service -f api.raml -p 4000